"""tests/unit/test_dashboard.py
Phase 12 — Streamlit Dashboard / User Interface Test Suite.

Contains exactly 13 test items verifying:
    1. Dashboard modules import successfully.
    2. Pipeline is invoked through the correct API (predict).
    3. No agent logic is duplicated in dashboard code.
    4. ACCEPT result renders correctly.
    5. REPAIR + VERIFIED result renders correctly.
    6. ESCALATE result renders correctly.
    7. REJECT result renders correctly.
    8. ERROR result renders correctly.
    9. Human-review flag renders prominent banner.
    10. Before/after repair display works when available.
    11. Dashboard does not mutate the original image.
    12. Research disclaimer is present and rendered.
    13. No clinical claims are generated by dashboard text.
"""

from __future__ import annotations

import ast
import hashlib
import io
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pytest
from PIL import Image

_SRC = Path(__file__).resolve().parent.parent.parent / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from cxr_reliability.contracts.base_model import BaseModelResult
from cxr_reliability.contracts.common import AgentName, DISCLAIMER
from cxr_reliability.contracts.decision import Action, DecisionResult
from cxr_reliability.contracts.ood import OODLevel, OODResult
from cxr_reliability.contracts.pipeline import (
    PipelineResult,
    PipelineState,
    PredictionSummary,
    ReliabilityLabel,
)
from cxr_reliability.contracts.quality import (
    DefectType,
    QualityFlags,
    QualityLevel,
    QualityResult,
)
from cxr_reliability.contracts.repair import RepairResult, RepairStep
from cxr_reliability.contracts.uncertainty import UncertaintyLevel, UncertaintyResult
from cxr_reliability.contracts.verification import (
    NextStep,
    VerificationResult,
    VerificationStatus,
)
from cxr_reliability.dashboard import app, components
from cxr_reliability.dashboard.components import (
    RESEARCH_DISCLAIMER_TEXT,
    render_base_model_section,
    render_decision_section,
    render_disclaimer_banner,
    render_final_result,
    render_header,
    render_human_review_banner,
    render_ood_section,
    render_quality_section,
    render_repair_section,
    render_sidebar,
    render_uncertainty_section,
    render_verification_section,
)


# ── Helpers & Fixtures ───────────────────────────────────────────────────────


def make_dummy_quality(level=QualityLevel.GOOD) -> QualityResult:
    return QualityResult(
        agent=AgentName.QUALITY,
        version="0.7.0",
        laplacian_variance=250.0,
        blur_pct=5.0,
        snr_db=25.0,
        mean_intensity=120.0,
        histogram_std=40.0,
        flags=QualityFlags(blur=False, noise=False, exposure=False),
        overall=level,
        score=0.9,
        label=level.value,
        reasoning="Good quality radiograph",
    )


def make_dummy_base_model(prob=0.85) -> BaseModelResult:
    return BaseModelResult(
        agent=AgentName.BASE_MODEL,
        version="0.4.0",
        model_id="densenet121-res224-nih",
        target_pathology="Pneumonia",
        pneumonia_logit=prob,
        pneumonia_probability=prob,
        all_pathology_outputs={"Pneumonia": prob, "Infiltration": 0.3},
        score=prob,
        label="Pneumonia" if prob >= 0.5 else "Non-Pneumonia",
        reasoning=f"Base model raw score: {prob:.4f}",
    )


def make_dummy_ood(level=OODLevel.IN_DISTRIBUTION) -> OODResult:
    return OODResult(
        agent=AgentName.OOD,
        version="0.5.0",
        mahalanobis_distance=12.5,
        mahalanobis_threshold=25.0,
        level=level,
        score=0.25,
        label=level.value,
        reasoning=f"OOD level evaluated as {level.value}",
    )


def make_dummy_uncertainty(level=UncertaintyLevel.LOW) -> UncertaintyResult:
    return UncertaintyResult(
        agent=AgentName.UNCERTAINTY,
        version="0.6.0",
        raw_model_score=0.85,
        confidence=0.85,
        entropy=0.25,
        normalized_entropy=0.25,
        uncertainty_level=level,
        score=0.85,
        label=level.value,
        reasoning="Low binary entropy",
    )


def make_dummy_decision(action=Action.ACCEPT) -> DecisionResult:
    return DecisionResult(
        agent=AgentName.DECISION,
        version="v1-0.8.0",
        action=action,
        rule_id="RULE-01",
        driving_signals={"quality": "good", "ood": "in_distribution"},
        reliability_label="accepted" if action == Action.ACCEPT else "needs_human_review",
        score=1.0,
        label=action.value,
        reasoning=f"Action decided: {action.value}",
    )


# ── 1. Dashboard Module Imports ───────────────────────────────────────────────


def test_dashboard_module_imports():
    """Test 1: Verify app and components modules import successfully."""
    import cxr_reliability.dashboard.app as app_mod
    import cxr_reliability.dashboard.components as comp_mod

    assert hasattr(app_mod, "main")
    assert hasattr(app_mod, "load_pipeline")
    assert hasattr(comp_mod, "render_disclaimer_banner")
    assert hasattr(comp_mod, "render_final_result")


# ── 2. Pipeline Invoked Through Correct API ───────────────────────────────────


def test_pipeline_invoked_via_predict_api():
    """Test 2: Verify dashboard invokes pipeline strictly through predict() API."""
    mock_pipeline = MagicMock()
    mock_result = PipelineResult(
        audit_id="test_001",
        pipeline_state=PipelineState.ACCEPT,
        final_action=Action.ACCEPT,
        reliability_label=ReliabilityLabel.ACCEPTED,
        needs_human_review=False,
        prediction=PredictionSummary(
            pneumonia_probability=0.75,
            positive=True,
            decision_threshold=0.5,
            source_model_id="densenet121",
        ),
        total_latency_ms=100.0,
        reason="Test accept",
    )
    mock_pipeline.predict.return_value = mock_result

    test_image = np.zeros((224, 224), dtype=np.uint8)
    res = mock_pipeline.predict(test_image, input_id="test_input")

    mock_pipeline.predict.assert_called_once_with(test_image, input_id="test_input")
    assert isinstance(res, PipelineResult)
    assert res.audit_id == "test_001"


# ── 3. No Agent Logic Duplicated in Dashboard ────────────────────────────────


def test_no_agent_logic_in_dashboard():
    """Test 3: Verify dashboard code does not duplicate agent calculations or decision logic."""
    dashboard_dir = _SRC / "cxr_reliability" / "dashboard"
    app_source = (dashboard_dir / "app.py").read_text(encoding="utf-8")
    comp_source = (dashboard_dir / "components.py").read_text(encoding="utf-8")

    forbidden_patterns = [
        "cv2.Laplacian",
        "scipy.spatial.distance.mahalanobis",
        "inv_cov",
        "rule_table",
        "clahe.apply",
        "bilateralFilter",
        "NextStep.RELEASE",  # Dashboard only reads result, does not decide next step
    ]

    for pattern in forbidden_patterns:
        assert pattern not in app_source, f"Agent logic duplicated in app.py: {pattern}"
        assert pattern not in comp_source, f"Agent logic duplicated in components.py: {pattern}"


# ── 4. ACCEPT Result Renders ─────────────────────────────────────────────────


def test_accept_result_renders():
    """Test 4: Verify rendering of an ACCEPT result."""
    result = PipelineResult(
        audit_id="audit_accept",
        pipeline_state=PipelineState.ACCEPT,
        final_action=Action.ACCEPT,
        reliability_label=ReliabilityLabel.ACCEPTED,
        needs_human_review=False,
        prediction=PredictionSummary(
            pneumonia_probability=0.82,
            positive=True,
            decision_threshold=0.5,
            source_model_id="densenet121-res224-nih",
        ),
        quality=make_dummy_quality(),
        base_model=make_dummy_base_model(0.82),
        ood=make_dummy_ood(),
        uncertainty=make_dummy_uncertainty(),
        decision_history=[make_dummy_decision(Action.ACCEPT)],
        total_latency_ms=120.0,
        reason="Accepted by Rule-01",
    )

    with patch("streamlit.metric") as mock_metric, patch("streamlit.columns") as mock_cols:
        mock_cols.return_value = [MagicMock(), MagicMock(), MagicMock(), MagicMock()]
        render_final_result(result)
        # Check that metric was called for ACCEPT
        calls = [c.args for c in mock_metric.call_args_list]
        state_calls = [c for c in calls if len(c) >= 2 and c[1] == "ACCEPT"]
        assert len(state_calls) > 0


# ── 5. REPAIR + VERIFIED Result Renders ───────────────────────────────────────


def test_repair_verified_result_renders():
    """Test 5: Verify rendering of a VERIFIED after-repair result."""
    repair_res = RepairResult(
        agent=AgentName.REPAIR,
        version="0.9.0",
        label="repaired",
        repaired=True,
        repair_applied=True,
        steps=[RepairStep(defect=DefectType.EXPOSURE, method="clahe", parameters={"clip": 2.0})],
        defects_detected=[DefectType.EXPOSURE],
        image_changed=True,
        reasoning="CLAHE repair applied",
    )
    verification_res = VerificationResult(
        agent=AgentName.VERIFICATION,
        version="0.10.0",
        verified=True,
        status=VerificationStatus.VERIFIED,
        next_step=NextStep.RELEASE,
        delta_confidence=0.18,
        delta_quality=15.0,
        delta_ood=-2.0,
        label_flipped=False,
        min_confidence_gain_used=0.15,
        threshold_is_provisional=True,
        score=0.18,
        label="verified",
        reasoning="Verification passed",
    )

    result = PipelineResult(
        audit_id="audit_verified",
        pipeline_state=PipelineState.VERIFIED,
        final_action=Action.ACCEPT,
        reliability_label=ReliabilityLabel.ACCEPTED_AFTER_REPAIR,
        needs_human_review=False,
        prediction=PredictionSummary(
            pneumonia_probability=0.88,
            positive=True,
            decision_threshold=0.5,
            source_model_id="densenet121",
        ),
        repair=repair_res,
        verification=verification_res,
        repair_attempts=1,
        total_latency_ms=250.0,
        reason="Repaired and verified",
        repaired_image_png=b"dummy_png_bytes",
    )

    with patch("streamlit.metric") as mock_metric, patch("streamlit.columns") as mock_cols:
        mock_cols.return_value = [MagicMock(), MagicMock(), MagicMock(), MagicMock()]
        render_final_result(result)
        render_verification_section(result.verification)

        metric_values = [c.args[1] for c in mock_metric.call_args_list if len(c.args) >= 2]
        assert "VERIFIED" in metric_values


# ── 6. ESCALATE Result Renders ───────────────────────────────────────────────


def test_escalate_result_renders():
    """Test 6: Verify rendering of an ESCALATE result with review required."""
    result = PipelineResult(
        audit_id="audit_escalate",
        pipeline_state=PipelineState.ESCALATE,
        final_action=Action.ESCALATE,
        reliability_label=ReliabilityLabel.NEEDS_HUMAN_REVIEW,
        needs_human_review=True,
        prediction=None,
        quality=make_dummy_quality(QualityLevel.DEGRADED),
        base_model=make_dummy_base_model(0.65),
        ood=make_dummy_ood(OODLevel.BORDERLINE),
        uncertainty=make_dummy_uncertainty(UncertaintyLevel.HIGH),
        decision_history=[make_dummy_decision(Action.ESCALATE)],
        total_latency_ms=90.0,
        reason="Borderline OOD and high uncertainty",
    )

    with patch("streamlit.metric") as mock_metric, patch("streamlit.error") as mock_error, patch("streamlit.columns") as mock_cols:
        mock_cols.return_value = [MagicMock(), MagicMock(), MagicMock(), MagicMock()]
        render_human_review_banner(result)
        render_final_result(result)

        mock_error.assert_called_once()
        assert "HUMAN REVIEW REQUIRED" in mock_error.call_args[0][0]


# ── 7. REJECT Result Renders ─────────────────────────────────────────────────


def test_reject_result_renders():
    """Test 7: Verify rendering of a REJECT result with review required."""
    result = PipelineResult(
        audit_id="audit_reject",
        pipeline_state=PipelineState.REJECT,
        final_action=Action.REJECT,
        reliability_label=ReliabilityLabel.NEEDS_HUMAN_REVIEW,
        needs_human_review=True,
        prediction=None,
        quality=make_dummy_quality(QualityLevel.POOR),
        base_model=make_dummy_base_model(0.50),
        ood=make_dummy_ood(OODLevel.SEVERE),
        uncertainty=make_dummy_uncertainty(UncertaintyLevel.HIGH),
        decision_history=[make_dummy_decision(Action.REJECT)],
        total_latency_ms=75.0,
        reason="Severe distribution shift and poor quality",
    )

    with patch("streamlit.metric") as mock_metric, patch("streamlit.error") as mock_error, patch("streamlit.columns") as mock_cols:
        mock_cols.return_value = [MagicMock(), MagicMock(), MagicMock(), MagicMock()]
        render_human_review_banner(result)
        render_final_result(result)

        mock_error.assert_called_once()
        state_values = [c.args[1] for c in mock_metric.call_args_list if len(c.args) >= 2]
        assert "REJECT" in state_values


# ── 8. ERROR Result Renders ─────────────────────────────────────────────────


def test_error_result_renders():
    """Test 8: Verify rendering of an ERROR pipeline state."""
    result = PipelineResult(
        audit_id="audit_error",
        pipeline_state=PipelineState.ERROR,
        final_action=Action.ESCALATE,
        reliability_label=ReliabilityLabel.NEEDS_HUMAN_REVIEW,
        needs_human_review=True,
        prediction=None,
        total_latency_ms=10.0,
        reason="Pipeline execution error occurred: model device failure",
        error_message="RuntimeError: CUDA out of memory",
    )

    with patch("streamlit.metric") as mock_metric, patch("streamlit.error") as mock_error, patch("streamlit.columns") as mock_cols:
        mock_cols.return_value = [MagicMock(), MagicMock(), MagicMock(), MagicMock()]
        render_human_review_banner(result)
        render_final_result(result)

        state_values = [c.args[1] for c in mock_metric.call_args_list if len(c.args) >= 2]
        assert "ERROR" in state_values


# ── 9. Human Review Flag Renders ─────────────────────────────────────────────


def test_human_review_flag_renders():
    """Test 9: Verify human review banner is shown when True and withheld when False."""
    res_review = PipelineResult(
        audit_id="a1",
        pipeline_state=PipelineState.ESCALATE,
        final_action=Action.ESCALATE,
        reliability_label=ReliabilityLabel.NEEDS_HUMAN_REVIEW,
        needs_human_review=True,
        reason="Requires clinical oversight",
    )
    with patch("streamlit.error") as mock_error:
        render_human_review_banner(res_review)
        mock_error.assert_called_once()
        assert "HUMAN REVIEW REQUIRED" in mock_error.call_args[0][0]

    res_no_review = PipelineResult(
        audit_id="a2",
        pipeline_state=PipelineState.ACCEPT,
        final_action=Action.ACCEPT,
        reliability_label=ReliabilityLabel.ACCEPTED,
        needs_human_review=False,
        prediction=PredictionSummary(
            pneumonia_probability=0.85,
            positive=True,
            decision_threshold=0.5,
            source_model_id="densenet121",
        ),
        reason="Valid input",
    )
    with patch("streamlit.error") as mock_error:
        render_human_review_banner(res_no_review)
        mock_error.assert_not_called()


# ── 10. Before/After Repair Display ──────────────────────────────────────────


def test_before_after_repair_display():
    """Test 10: Verify before and after images are displayed in columns when repair occurs."""
    repair_res = RepairResult(
        agent=AgentName.REPAIR,
        version="0.9.0",
        label="repaired",
        repaired=True,
        repair_applied=True,
        steps=[RepairStep(defect=DefectType.EXPOSURE, method="clahe", parameters={})],
        defects_detected=[DefectType.EXPOSURE],
        image_changed=True,
        reasoning="Repair executed",
    )

    original_img = Image.new("L", (100, 100), color=128)
    dummy_png = b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR"

    with patch("streamlit.image") as mock_image, patch("streamlit.columns") as mock_cols:
        col1 = MagicMock()
        col2 = MagicMock()
        mock_cols.return_value = [col1, col2]

        render_repair_section(repair_res, original_img, dummy_png)
        assert mock_image.call_count == 2


# ── 11. Dashboard Does Not Mutate Original Image ─────────────────────────────


def test_dashboard_does_not_mutate_original_image():
    """Test 11: Verify image processing does not alter original image bytes."""
    original_arr = np.random.randint(0, 256, (224, 224), dtype=np.uint8)
    sha_before = hashlib.sha256(original_arr.tobytes()).hexdigest()

    pil_img = Image.fromarray(original_arr)
    # Replicate dashboard image conversion
    arr_processed = np.array(pil_img.convert("L"))

    sha_after = hashlib.sha256(original_arr.tobytes()).hexdigest()
    assert sha_before == sha_after, "Original array data was mutated!"
    assert np.array_equal(original_arr, arr_processed)


# ── 12. Disclaimer Is Present ────────────────────────────────────────────────


def test_disclaimer_is_present():
    """Test 12: Verify research disclaimer is present in dashboard components."""
    with patch("streamlit.warning") as mock_warning:
        render_disclaimer_banner()
        mock_warning.assert_called_once()
        assert "Research prototype only" in mock_warning.call_args[0][0]

    with patch("streamlit.title"), patch("streamlit.caption"), patch("streamlit.divider"), patch("streamlit.warning") as mock_warning:
        render_header()
        mock_warning.assert_called_once()


# ── 13. No Clinical Claims in Dashboard Copy ─────────────────────────────────


def test_no_clinical_claims_in_dashboard():
    """Test 13: Strict check ensuring no clinical diagnostic claims exist in dashboard text."""
    dashboard_dir = _SRC / "cxr_reliability" / "dashboard"
    app_text = (dashboard_dir / "app.py").read_text(encoding="utf-8").lower()
    comp_text = (dashboard_dir / "components.py").read_text(encoding="utf-8").lower()

    forbidden_phrases = [
        "confirmed pneumonia",
        "no pneumonia detected",
        "patient is healthy",
        "patient has pneumonia",
        "clinically safe",
        "medically validated",
        "diagnostic confirmation",
        "prescribe",
    ]

    for phrase in forbidden_phrases:
        assert phrase not in app_text, f"Forbidden clinical phrase found in app.py: '{phrase}'"
        assert phrase not in comp_text, f"Forbidden clinical phrase found in components.py: '{phrase}'"
